### ISSUE TITLE
Getting plain text error when OAuth disconnected

### ISSUE THREAD

**Issue by Joel-James** [CodeMillApp/support#2]
When I disconnect OAuth access from my GitHub account and try to access **[My Organizations](http://codemill.io/clients/orgs)** page (few other pages too) in CodeMill, it shows error in plain text format. This exception should be handled properly right?

![firefox_screenshot_2016-03-15t04-40-06 278z](https://cloud.githubusercontent.com/assets/7510463/13767921/2b653fc2-ea96-11e5-8f2f-edd1dc13f991.png)

**Comment by CodeMillApp** [comment]
Absolutely right. We were very forgiving in handling UI of exceptions. Simply sending each of them to be displayed in an error page. Good for development, not so friendly for production.

BTW why did you disconnect oauth?

**Comment by Joel-James** [comment]
Nothing serious! I was trying it out. Awesome service anyway :+1:
