### ISSUE TITLE
Fixed and closed task has been picked up by dev

### ISSUE THREAD

**Issue by kenorb** [CodeMillApp/support#26]
The task (5800fda4c892d900033f4f70) has been fixed and PR merged, and I believe it was already paid, but somehow it's still flying around in Codemill and it appeared in _Open Tasks_, now again in _Tasks in Development_, because now somebody picked this up. Please fix it.

I had to manually _Unassign_ the person to avoid any further confusion, which caused another one-time [issue](CodeMillApp/support/issues/27).

**Comment by CodeMillApp** [comment]
Fixed. Thanks.
