### ISSUE TITLE
superfluous oauth request

### ISSUE THREAD

**Issue by kaizensoze** [CodeMillApp/support#3]
Why make two oauth requests? Instead of requesting public info and then email, just request `user:email` from the start. The `user:email` scope should include public info.

**Comment by CodeMillApp** [comment]
The thing with GitHub API, is that it's not really built for a "sign in with" functionality. They have a weird behavior, that if you send a user with a `scope` that is not empty (i.e. user:email) then it is implicitly suggested that you want to remove all other permissions that aren't mentioned in the scope. 

That's not that bad if you already have the user signed in and can query the API for their existing permissions and build the `scope` param correctly for following calls (i.e. if you want to add a permission).

But when you have a user signed out, and you want to have them signed in with github, then if you send only the `user:email` it will remove all other permissions! The only way to work around it is to use an empty `scope`. 

It is not well documented, [only implied](https://developer.github.com/v3/oauth/#1-redirect-users-to-request-github-access) but I got that finally by emailing with their excellent support team.
I know it's a bummer and I hope they fix it, but this is just how things are currently.

**Comment by kaizensoze** [comment]
Ah ok I didn't realize more permissions [like repo] are requested at a later point in time as needed. I'm used to apps asking for everything up front as a one time thing.

**Comment by shaharsol** [comment]
Would you prefer it that way? Would you sign up in the first place if I asked all the possible permissions I use in advance?

**Comment by kaizensoze** [comment]
What is the complete scope list needed by the app?

**Comment by CodeMillApp** [comment]
It really depends on your role and preferences.
If you're a developer, you will most commonly need `email,public_repo`
If you're working on a clients private repo, you'll also need `repo`.
If you're a client you'll also need some `hook` permissions, either for `org` or `repo`

**Comment by kaizensoze** [comment]
Yeah I guess due to the different roles, the piecemeal approach makes more sense despite it being more of a pain to implement.
