### ISSUE TITLE
Send emails when new task in the marketpalce

### ISSUE THREAD

**Issue by Progi1984** [CodeMillApp/support#4]
CodeMillApp could send mail when new tasks (with filter) are available in the marketplace.

**Comment by CodeMillApp** [comment]
You'd bet it's high on our priority list! I hope we will push it soon. In the meantime we send a daily digest, it's not optimal, but it's informative and may help you match with a task.

**Comment by cookiengineer** [comment]
I would also add a small message in case no new tasks are available. Currently, it seems like something JS-related went wrong and I bet new users like me are all unsure if everything worked correctly with the github auth.

**Comment by CodeMillApp** [comment]
@Progi1984 just soft launched it... care to provide feedback? http://codemill.io/developers/alerts

**Comment by Progi1984** [comment]
Perfect :)
