### ISSUE TITLE
Grabbing the test task does not work

### ISSUE THREAD

**Issue by digilist** [CodeMillApp/support#5]
The link to the issue (https://github.com/odises/CodeMillTest/issues/3) and the grabbing of the task does not work. I am getting a 

> error in fork 404 : {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

Probably the link to the repository is just wrong :smile:

**Comment by ghost** [comment]
I think it happened because the owner deleted or made the repository private. CodeMill should track this error and remove the task.

**Comment by CodeMillApp** [comment]
@imunolion you're right. and we're on it.
