### ISSUE TITLE
Empty marketplace

### ISSUE THREAD

**Issue by memoryonrepeat** [CodeMillApp/support#9]
Hi, I signed up a couple days ago but still haven't seen any task available in the marketplace. Is it just me or there is actually a lack of available tasks at the moment (I signed up using the current github account) ?

**Comment by CodeMillApp** [comment]
@tienthanh8490 there is currently an imbalance in the demand/supply ratio, which causes each submitted task to be grabbed within a very short time. I hope we can drive more tasks to balance the market.

**Comment by goloroden** [comment]
Hm. This was ~6 weeks ago, and the situation apparently didn't change… :-(

**Comment by CodeMillApp** [comment]
We're working on it. It is very challenging indeed but we are on it.
